Repository brabbuss/moodytunes, pull requests merged in 2021-01, with the labels that each got.

#19 Display results
  src/components/App/App.tsx
  src/components/Form/Form.tsx
  src/components/Result/Result.css
  src/components/Result/Result.tsx
  src/components/ResultsView/ResultsView.tsx
  src/utilities/apiCalls.ts
Labels: enhancement

#23 Typescript errors and Implement Router
  src/components/App/App.tsx
  src/components/FavoritesView/FavoritesView.tsx
  src/components/Form/Form.tsx
  src/components/Result/Result.tsx
  src/components/ResultsView/ResultsView.tsx
  src/components/common/Types.ts
  src/index.tsx
  src/utilities/apiCalls.ts
Labels: bug, enhancement

#27 Feature favorites
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/Favorite/Favorite.css
  src/components/Favorite/Favorite.tsx
  src/components/FavoritesView/FavoritesView.css
  src/components/FavoritesView/FavoritesView.tsx
  src/components/Form/Form.css
  src/components/Form/Form.test.tsx
  src/components/Form/Form.tsx
  src/components/Result/Result.css
  src/components/Result/Result.tsx
  src/components/ResultsView/ResultsView.css
  src/components/ResultsView/ResultsView.tsx
  src/components/common/Types.ts
  src/utilities/apiCalls.ts
Labels: enhancement

#33 Feature failures
  src/components/App/App.tsx
  src/components/Form/Form.css
  src/components/Form/Form.tsx
  src/components/Result/Result.tsx
  src/components/ResultsView/ResultsView.tsx
  src/icons/angry.svg
  src/icons/content.svg
  src/icons/happy.svg
  src/icons/sad.svg
Labels: UI/UX, enhancement

#36 Feature favorites storage
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/Favorite/Favorite.css
  src/components/Favorite/Favorite.tsx
  src/components/FavoritesView/FavoritesView.css
  src/components/FavoritesView/FavoritesView.tsx
  src/components/Form/Form.css
  src/components/Form/Form.tsx
  src/components/Result/Result.css
  src/components/Result/Result.tsx
  src/components/ResultsView/ResultsView.css
  src/utilities/useLocalStorage.tsx
Labels: UI/UX, enhancement

#40 Styling results favorites
  package-lock.json
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/Favorite/Favorite.css
  src/components/FavoritesView/FavoritesView.tsx
  src/components/Form/Form.tsx
  src/icons/angry.svg
  src/icons/content.svg
  src/icons/happy.svg
  src/icons/sad.svg
  src/utilities/icons.js
Labels: UI/UX, enhancement

#42 Form moods
  src/components/App/App.tsx
  src/components/Favorite/Favorite.css
  src/components/Form/Form.css
  src/components/Form/Form.tsx
  src/components/ResultsView/ResultsView.tsx
  src/components/common/Types.ts
  src/utilities/icons.js
Labels: enhancement

#48 Feature navbar
  src/components/App/App.tsx
  src/components/Form/Form.css
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.tsx
  src/components/Result/Result.css
  src/utilities/icons.js
Labels: UI/UX, enhancement

#58 Styling favorites view
  src/components/FavoritesView/FavoritesView.css
  src/components/FavoritesView/FavoritesView.tsx
  src/components/NavBar/NavBar.css
  src/utilities/icons.js
Labels: enhancement
